# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ipgeobase', '0002_ipgeobase_city_id'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='ipgeobase',
            index_together=set([('start_ip', 'end_ip')]),
        ),
    ]
